### ISSUE TITLE
How do we build this?

### ISSUE THREAD

**Issue by darkedges** [ForgeRock/openbanking-directory#1]
Thanks for releasing the Open Banking Directory.

How do I build this? Do I need a ForgeRock Account with access to some repository?

When I try and build it is looking for `forgerock-openbanking-starter-parent` which I assume is somewhere in this repository.

Regards
Nicholas Irving
DarkEdges

**Comment by darkedges** [comment]
Found `forgerock-openbanking-starter-parent`  at https://github.com/ForgeRock/openbanking-parent

**Comment by benjefferies** [comment]
Hi Nick, we've moved all of our open sourced reference implementation to a new organisation https://github.com/OpenBankingToolkit/. Over the next few days we'll be removing these repos that are left over. The equivalent repository you'll be looking for is https://github.com/OpenBankingToolkit/openbanking-directory. Over then next few days we'll be focusing on our documentation for the developer community. In the meantime you'll need to add the open banking bintray repository until we've fully migrated to jcenter. We'll be adding this to the docs

```
<?xml version="1.0" encoding="UTF-8" ?>
<settings xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd'
          xmlns='http://maven.apache.org/SETTINGS/1.0.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
    
    <profiles>
        <profile>
            <repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-openbanking-toolkit-OpenBankingToolKit</id>
                    <name>bintray</name>
                    <url>https://dl.bintray.com/openbanking-toolkit/OpenBankingToolKit</url>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-openbanking-toolkit-OpenBankingToolKit</id>
                    <name>bintray-plugins</name>
                    <url>https://dl.bintray.com/openbanking-toolkit/OpenBankingToolKit</url>
                </pluginRepository>
            </pluginRepositories>
            <id>bintray</id>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>bintray</activeProfile>
    </activeProfiles>
</settings>
```

**Comment by benjefferies** [comment]
The best example of how to use the openbanking toolkit is the reference implementation https://github.com/OpenBankingToolkit/openbanking-reference-implementation whilst we're improving the docs
